POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhdHVzYWkiLCJpZCI6IjY3M2E4YjllNzI4ODVlMGIyMjA3NjY1ZSIsImlhdCI6MTczMjAyMTgyOCwiZXhwIjoxNzMyMDI1NDI4fQ.nsurBbaTMYG5v5KrzEZNOjVmfxYyf62WpjN2pu6EZeM

{
  "title": "prueba2",
  "author": "ema",
  "url": "String",
  "likes": 100
}